disable debug mode

diff --git a/postinstall b/postinstall
--- a/postinstall
+++ b/postinstall
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-set -Euxo pipefail
-trap 'echo "Error on line $LINENO: $BASH_COMMAND" >&2' ERR
+#set -Euxo pipefail
+#trap 'echo "Error on line $LINENO: $BASH_COMMAND" >&2' ERR
 
 if [[ -f $PWD/sharedfuncs ]]; then
 	source sharedfuncs
@@ -63,11 +63,11 @@ install_packages() {
 }
 
 activate_services() {
-	awk 1 "$@" | sed -n -e "s/^[ \t]*systemctl enable --now[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | xargs -r -n1 -I{} sudo systemctl enable {}
+	awk 1 "$@" | sed -n -e "s/^[ \t]*systemctl enable --now[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | xargs -r -I{} sudo systemctl enable {}
 }
 
 add_groups() {
-	awk 1 "$@" | sed -n -e "s/^[ \t]*gpasswd -a USERNAME[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | xargs -r -n1 -I{} sudo gpasswd -a "${USER}" {}
+	awk 1 "$@" | sed -n -e "s/^[ \t]*gpasswd -a USERNAME[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | xargs -r -I{} sudo gpasswd -a "${USER}" {}
 }
 
 ## -------------------------------------------------------
@@ -152,7 +152,7 @@ activate_services ${arch_dir}/post_install/070_System.md
 
 cecho "CLEAN ORPHAN PACKAGES - https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Removing_unused_packages_.28orphans.29"
 
-sudo pacman -Rcns --noconfirm "$(pacman -Qqdt)"
+pkgs_to_clean=$(pacman -Qqdt) && [ -n "$pkgs_to_clean" ] && sudo pacman -Rcns --noconfirm $pkgs_to_clean
 
 paccache -r -k 0
 sudo pacman -Scc --noconfirm
